services:
  - type: web
    name: edytor-stron
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health
