services:
  - type: web
    name: edytor-stron
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm run render-build
    startCommand: NODE_ENV=production node backend/dist/index.js
    healthCheckPath: /api/health
