services:
  - type: web
    name: edytor-stron
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install --include=dev && npm run install:all && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
